plt.figure(figsize=(8, 5))
sns.barplot(x=full_df['Year'], y=full_df['Steel_Exports'], palette="Blues_d")
plt.axhline(pre_tariff_steel, color='red', linestyle='--', label='Pre-Tariff Level (2018)')
plt.title('Steel Exports to US (2018–2024) with Tariff Benchmark')
plt.xlabel('Year')
plt.ylabel('Steel Exports (Billions USD)')
plt.legend()
plt.tight_layout()
plt.show()
