plt.figure(figsize=(8, 5))
plt.plot(y_test.values, label='Actual Trade Balance', marker='o')
plt.plot(y_pred, label='Predicted Trade Balance', marker='x')
plt.title('Actual vs Predicted Trade Balance (Linear Regression)')
plt.xlabel('Test Sample Index')
plt.ylabel('Trade Balance (Billions USD)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()